### ISSUE TITLE
Create a release?

### ISSUE THREAD

**Issue by smintz** [stephenafamo/orchestra#5]
Hey,
You probably noticed I am using this great lib! Would you be kind and create a version for this repo (v0.1.0 seems like a good one). It will help others by automatically creating documentation in https://pkg.go.dev and will allow you to keep developing here without introducing breaking changes :)

**Comment by stephenafamo** [comment]
Well... there is documentation on pkg.go.dev <https://pkg.go.dev/github.com/stephenafamo/orchestra>.

But I do see why tagging a version would be nice. I'll create a tag once we finalize your PR

**Comment by stephenafamo** [comment]
Done.
